plugins {
    id("org.gradle.toolchains.foojay-resolver-convention") version "0.8.0"
}
rootProject.name = "kotlin-illustrated-guide"
include("chapter01")
include("chapter02")
include("chapter03")
include("chapter04")
include("chapter05")
include("chapter06")
include("chapter07")
include("chapter08")
include("chapter09")
include("chapter10")
include("chapter11")
include("chapter12")
include("chapter13")
include("chapter14")
include("chapter15")
include("chapter16")
include("chapter17")
include("chapter18")
include("chapter19")
include("chapter20")
include("example")
